#!/bin/sh

if [ "$(uci get autoupdater.stable.mirror | grep firmware.*4830.org >/dev/null ; echo $?)" = "0" ]; then
 logger "4830.org FW detected! Move on, nothing to see here!"
 exit 0
fi

echo "$0 start." | tee -a /root/multidomain-migration.log

hostname="$(pretty-hostname | sed -e 's/"/-/g')"
hostname="$(echo -n "$hostname" | sed -r -e 's/ä/ae/g' -e 's/ö/oe/g' -e 's/ü/ue/g' -e 's/ß/sz/g' -e 's/Ä/Ae/g' -e 's/Ö/Oe/g' -e 's/Ü/Ue/g')"
hostname="$(echo -n "$hostname" | sed -r -e 's/[^a-zA-Z0-9-]/-/g')"
hostname="$(echo -n "$hostname" | sed -r -e 's/-+/-/g' -e 's/^-//')"
hostname="${hostname:0:63}"
hostname="$(echo -n "$hostname" | sed -e 's/-$//')"

curdom="$(uci get gluon.core.domain 2>/dev/null ||:)"
domain="${curdom}"
if [ "X${domain}" = "X" ]; then
 domain="zzz"
fi

if [ "$(uci get autoupdater.stable.mirror | grep freifunk-lippe.de >/dev/null ; echo $?)" = "0" ]; then
 echo "Migrating FFLIP-FW to 4830.org FW ..." | tee -a /root/multidomain-migration.log

 # FIXUPs
 for file in 550-rsk-config 888-button-bind
 do
   if [ -e /lib/gluon/upgrade/${file} ]; then
     echo -e "#!/bin/sh\nexit 0" >/lib/gluon/upgrade/${file} ||:
     chmod +x /lib/gluon/upgrade/${file} ||:
     echo "${file}" >> /tmp/need-upgrade-fixup
   fi
 done
 if [ -h /etc/profile ]; then
  rm /etc/profile && cp -p /rom/etc/profile /etc/profile
 fi

 olddom=$(uci get gluon.core.domain)
 domain=$(echo ${olddom} | sed -e s/d1/bmg/ -e s/d2/det/ -e s/d3/lem/ -e s/d4/bfn/ -e s/d7/xx7/ -e s/d8/xx8/)
 if [ ! -e /lib/gluon/domains/${domain}.json ]; then
  domain="lem"
 fi
 lat=$(uci get gluon-node-info.@location[0].latitude 2>/dev/null || echo "0.00")
 lon=$(uci get gluon-node-info.@location[0].longitude 2>/dev/null || echo "0.00")
 if [ "$lat" != "0.00" -a "$lon" != "0.00" ]; then
  if [ "$(echo "$lat;$lon" | awk 'BEGIN{FS=";";} {if($1<51.72830 && $2<8.33347) {printf("true");} else {printf("false");}}')" = "true" ]; then
   echo "Geolocation based migration moves node $hostname from ${domain} to 4830.org's mns ..." | tee -a /root/multidomain-migration.log
   domain="mns"
  fi
 fi
 if [ "$(echo $hostname | grep '^SPK-PB-DT-HX' >/dev/null ; echo $?)" = "0" ]; then
  if [ "${domain}" != "xx8" ]; then
   echo "Name based migration moves node $hostname from ${domain} to 4830.org's xx8 ..." | tee -a /root/multidomain-migration.log
   domain="xx8"
  fi
 fi
 if [ "$(echo $hostname | grep -- '-krvw$' >/dev/null ; echo $?)" = "0" ]; then
  if [ "${domain}" != "xx7" ]; then
   echo "Name based migration moves node $hostname from ${domain} to 4830.org's xx7 ..." | tee -a /root/multidomain-migration.log
   domain="xx7"
  fi
 fi
 echo "Migrating FFLIP-FW, mesh ${olddom}, to 4830.org's ${domain} ..." | tee -a /root/multidomain-migration.log
else
 echo "Migrating alien FW to 4830.org FW ..." | tee -a /root/multidomain-migration.log

 # FIXUP
 if [ -h /etc/profile ]; then
  rm /etc/profile && cp -p /rom/etc/profile /etc/profile
 fi
fi

if [ ! -e /lib/gluon/domains/${domain}.json ]; then
 echo "No match for mesh ${domain} in /lib/gluon/domains/, setting to default (zzz)." | tee -a /root/multidomain-migration.log
 domain="zzz"
fi

echo "Selected Domain: ${domain}." | tee -a /root/multidomain-migration.log

if [ "${curdom}" != "${domain}" ]; then
 echo "Setting domain: ${domain}." | tee -a /root/multidomain-migration.log
 uci set gluon.core.domain="${domain}" ||:
 uci commit gluon ||:
 #echo "Will run 'gluon-reconfigure 2>&1' later" | tee -a /root/multidomain-migration.log
 #touch /tmp/need-gluon-reconfigure
 gluon-reconfigure 2>&1 | tee /root/migration-gluon-reconfigure.log
else
 echo "Domain ${domain} already set." | tee -a /root/multidomain-migration.log
fi

echo "$0 done." | tee -a /root/multidomain-migration.log
