#!/bin/sh

if [ -e /tmp/need-upgrade-fixup ]; then
 for file in $(cat /tmp/need-upgrade-fixup)
 do
   if [ -e /lib/gluon/upgrade/${file} ]; then
     echo "$0: Removing /lib/gluon/upgrade/${file} ..." | tee -a /root/multidomain-migration.log
     rm /lib/gluon/upgrade/${file} ||:
   fi
 done
fi

if [ -e /tmp/need-gluon-reconfigure ]; then
 rm /tmp/need-gluon-reconfigure ||:
 ((sleep 2 ; gluon-reconfigure 2>&1 | tee /root/migration-gluon-reconfigure.log ; sync; sync; sleep 5 ; sync; reboot)&)
fi
