#!/usr/bin/lua

local minute = math.random(0, 59)

-- Scan hourly at a random time
local f = io.open('/usr/lib/micron.d/channel-survey', 'w')
f:write(string.format('%i * * * * /usr/sbin/channel-survey > /tmp/gluon/channel-survey.cache\n', minute))
f:close()
