#!/bin/sh

MODEL=/tmp/sysinfo/model
if [ ! -e ${MODEL} ]; then
  MODEL=/tmp/banner
  awk </proc/cpuinfo '/^model name/ {model=substr($0, index($0, ":")+2);} END{print model;}' >>${MODEL}
else
  cp ${MODEL} /tmp/banner
fi

grep OpenWrt /etc/banner.openwrt >/dev/null
RC=$?
if [ ${RC} == 0 ]; then
  OS="$(echo -e "`grep ', r' /etc/banner.openwrt | sed -e 's/.*(\(.*\)).*$/\1/' -e 's/ OpenWrt //g'`")"
else
  OS="$(echo -e "`grep ', r' /etc/banner.openwrt | sed -e 's/.*(\(.*\)).*$/\1/'`")"
fi

grep "^  OS: " /etc/banner >/dev/null || echo -e "OS: ${OS}\nHW: `cat /tmp/banner`\nFW: `cat /lib/gluon/release`" | \
 awk 'BEGIN{l=0} {line[l++]=$0;} END{printf("\n  %-36.36s    %-36.36s\n  %-72.72s\n", line[0], line[2], line[1]);}' >>/etc/banner
