#!/usr/bin/lua

local uci = require('simple-uci').cursor()

-- Create UCI configuration file if not present
os.execute("touch /etc/config/ffgt")
os.execute("touch /lib/gluon/upgrade/955-ffda-geolocator")
os.execute("rm /lib/gluon/upgrade/955-ffda-geolocator")

-- Create UCI section
if uci:get("ffgt", "geolocator", "enabled") == nil then
	uci:section('ffgt', 'geolocator', 'geolocator', {
		enabled = '1',
		update_interval = '10',
		min_distance = '250',
		min_accuracy = '150',
	})
	uci:commit("ffgt")
end

if not uci:get_bool("ffgt", "geolocator", "enabled") then
	return
end

-- Execute locator every 10 minutes
local f = io.open("/usr/lib/micron.d/ffgt-geolocator", 'w')
f:write("*/10 * * * *  /usr/bin/ffgt-geolocate --cron\n")
f:close()
