#!/bin/sh

for i in $(uci get autoupdater.stable.mirror)
do
 meshname=$(echo $i | awk '{gsub("/$", "", $1); gsub("/stable/sysupgrade", "", $1); n=split($1, a, "/"); printf("%s", a[n]);}')
done

if [ "${meshname}" = "unified" ]; then
 echo "Welcome to Uelzen Unified Firmware!" | tee /tmp/multidomain-migration.log
 exit 0
fi

echo "Migrating FFUE-FW for ${meshname} to Uelzen Unified Firmware ..." | tee -a /tmp/multidomain-migration.log

domain=$(echo ${meshname} | sed -e s/uelzen/uel/ -e s/celle/cel/ -e s/gifhorn/gif/ -e s/bienenbuettel/xbj/)
if [ ! -e /lib/gluon/domains/${domain}.json ]; then
 echo "No match for mesh ${domain} in /lib/gluon/domains/, setting to default (uez)." | tee -a /tmp/multidomain-migration.log
 domain=uez
fi

echo "Selected Domain: ${domain}." | tee -a /tmp/multidomain-migration.log

curdom=$(uci get gluon.core.domain)
if [ "${curdom}" != "${domain}" ]; then
 echo "Setting domain: ${domain}." | tee -a /tmp/multidomain-migration.log
 uci set gluon.core.domain=${domain} ||:
 uci commit gluon ||:
 gluon-reconfigure 2>&1 | tee -a /tmp/multidomain-migration.log
else
 echo "Domain ${domain} already set." | tee -a /tmp/multidomain-migration.log
fi
