#!/bin/sh

if [ "$(uci get autoupdater.stable.mirror | grep ffue >/dev/null ; echo $?)" != "0" ]; then
 echo "Not an FFUE Firmware!" | tee -a /tmp/multidomain-migration.log
 exit 0
fi

for i in $(uci get autoupdater.stable.mirror)
do
 meshname=$(echo $i | awk '{gsub("/$", "", $1); gsub("/stable/sysupgrade", "", $1); n=split($1, a, "/"); printf("%s", a[n]);}')
done

if [ "${meshname}" = "unified" ]; then
 echo "Welcome to Uelzen Unified Firmware! Nothing to do." | tee -a /tmp/multidomain-migration.log
 exit 0
fi

echo "Migrating FFUE-FW for ${meshname} to 4830.org Firmware ..." | tee -a /tmp/multidomain-migration.log

domain=$(echo ${meshname} | sed -e s/uelzen/uel/ -e s/celle/cel/ -e s/gifhorn/gif/ -e s/bienenbuettel/xbj/ -e s/wendland/luw/)
if [ ! -e /lib/gluon/domains/${domain}.json ]; then
 echo "No match for mesh ${domain} in /lib/gluon/domains/, setting to default (uez)." | tee -a /tmp/multidomain-migration.log
 domain=uez
fi
if [ ! -e /lib/gluon/domains/${domain}.json ]; then
 echo "Oops. Firmware not prepared for ${domain}, setting to fallback (zzz)." | tee -a /tmp/multidomain-migration.log
 domain=zzz
fi

echo "Selected mesh: ${domain}." | tee -a /tmp/multidomain-migration.log

curdom=$(uci get gluon.core.domain)
if [ "${curdom}" != "${domain}" ]; then
 echo "Setting mesh (domains) to ${domain}." | tee -a /tmp/multidomain-migration.log
 uci set gluon.core.domain=${domain} ||:
 uci commit gluon ||:
 gluon-reconfigure 2>&1 | tee -a /tmp/multidomain-migration.log
else
 echo "Mesh ${domain} already set." | tee -a /tmp/multidomain-migration.log
fi
