#!/bin/sh

N1="$(get_image_name)"
N2="${N1%-*}"

RC1="$(grep "${N1}" /lib/gluon/eol-devices >/dev/null ; echo $?)"
RC2="$(grep "${N2}" /lib/gluon/eol-devices >/dev/null ; echo $?)"
branch=$(uci get autoupdater.settings.branch)

# Skip for fake branch mns
if [ "${branch}" = "mns" ]; then
  exit 0
fi

if [ $RC1 -eq 0 -o $RC2 -eq 0 ]; then
  branch=$(uci get autoupdater.settings.branch)
  if [ "${branch}" != "deadend" ]; then
    uci set autoupdater.settings.branch='deadend'
    uci commit autoupdater
    HOSTNAME="$(uci get system.@system[0].hostname)"
    uci set system.@system[0].hostname="$(echo ${HOSTNAME})-EOL"
    uci commit system
  fi
fi
