#!/usr/bin/lua

local site = require 'gluon.site_config'
local users = require 'gluon.users'
local util = require 'gluon.util'

local uci = require('simple-uci').cursor()

local tunneldigger_enabled = uci:get_first('tunneldigger', 'broker', 'enabled')
local fastd_enabled = uci:get('fastd', 'mesh_vpn', 'enabled')

local tunneldigger_installed = tonumber(util.exec('/usr/bin/test -e /usr/bin/tunneldigger; echo -n $?'))
local fastd_installed = tonumber(util.exec('/usr/bin/test -e /usr/bin/fastd; echo -n $?'))

if (tunneldigger_installed == 0) then
  tunneldigger_installed = 1
else
  tunneldigger_installed = 0
end
if (fastd_installed == 0) then
  fastd_installed = 1
else
  fastd_installed = 0
end

local enabled = 0

if (tonumber(tunneldigger_enabled) == 1 or tonumber(fastd_enabled) == 1) then
  enabled = 1
end

if (enabled == 1) then
  if (tunneldigger_installed == 1 and fastd_installed == 0) then
    uci:set("tunneldigger", uci:get_first("tunneldigger", "broker"), "enabled", enabled)
    uci:save("tunneldigger")
    uci:commit("tunneldigger")
  elseif (tunneldigger_installed == 0 and fastd_installed == 1) then
    uci:set("fastd", "mesh_vpn", "enabled", enabled)
    uci:save("fastd")
    uci:commit("fastd")
  end
end
