#!/bin/sh /etc/rc.common

START=14


boot() {
    if [ -e /etc/config/freifunk ]; then
        (
        set -x
        df -h
        #(cd /etc ; tar cf /tmp/configs.tar config/dropbear passwd shadow dropbear) ||:
        #cp -p /etc/config/freifunk /tmp/freifunk && yes | firstboot
        #mkdir -p /etc/config/ ||:
        #cp -p /tmp/freifunk /etc/config/freifunk-bi ||:
        #(cd /etc ; tar xf /tmp/configs.tar) ||:
        mv /etc/config/freifunk /etc/config/freifunk-bi
        cd /overlay/upper/etc/config && /bin/rm -rf batman-adv autoupdater alfred dhcp fastd firewall network simple-radvd system uhttpd wireless gluon* ||:
        #for i in batman-adv autoupdater alfred dhcp fastd firewall  gluon gluon-core gluon-node-info gluon-setup-mode gluon-wan-dnsmasq network simple-radvd system uhttpd wireless
        #do
        #    uci import $i </dev/null
        #    uci commit $i
        #done
        sync
        ) > /root/migrate-ffbi-phase-0.log 2>&1
        /etc/init.d/done boot
        reboot
    fi

    if [ -e /etc/config/freifunk-bi ]; then
        (
        set -x
        uci set gluon-node-info.\@owner\[0\].contact="$(uci -q get 'freifunk-bi.@settings[0].contact')" ||:
        uci set gluon-node-info.\@location\[0\].latitude="$(uci -q get 'freifunk-bi.@settings[0].latitude')" ||:
        uci set gluon-node-info.\@location\[0\].longitude="$(uci -q get 'freifunk-bi.@settings[0].longitude')" ||:
        uci set gluon-node-info.\@location\[0\].share_location='1' ||:
        uci set gluon-setup-mode.\@setup_mode\[0\].configured='1' ||:
        SHOWONMAP="$(uci -q get 'freifunk-bi.@settings[0].publish_map')"
        if [ "$SHOWONMAP" = "none" ]; then
            uci set gluon-node-info.\@location\[0\].share_location='0' ||:
        fi
        MESHONLAN="$(uci -q get 'freifunk-bi.@settings[0].mesh_on_wan')"
        if [ "$MESHONLAN" = "1" ]; then
            uci set network.mesh_wan.disabled='0' ||:
        fi
        TCENABLED="$(uci -q get 'simple-tc.@interface[0].enabled')"
        if [ "$TCENABLED" = "1" ]; then
            uci -q get gluon.mesh_vpn
            if [ $? -eq 1 ]; then
                uci set gluon.mesh_vpn=mesh_vpn
            fi
            uci set gluon.mesh_vpn.limit_enabled='1' ||:
            uci set gluon.mesh_vpn.limit_ingress="$(uci -q get 'simple-tc.@interface[0].limit_ingress')" ||:
            uci set gluon.mesh_vpn.limit_egress="$(uci -q get 'simple-tc.@interface[0].limit_egress')" ||:
        fi
        if [ -e /lib/gluon/ffgt-geolocate/rgeo.sh ]; then
            COUNT=12
            while [ $COUNT -gt 0 ]
            do
              ip -4 route show | grep ^default >/dev/null 2>&1
              if [ $? -eq 0 ]; then
                break
              fi
              COUNT=$(expr $COUNT - 1)
              sleep 10
            done
            /lib/gluon/ffgt-geolocate/rgeo.sh ||:
        fi
        uci set gluon.core.domain='xzx'
        uci set gluon-node-info.\@location\[0\].locode='xzx'
        uci set gluon-node-info.\@location\[0\].sitelesect='xzx'
        /bin/pretty-hostname "$(uci -q get 'freifunk-bi.@settings[0].name')" ||:
        for i in gluon gluon-node-info gluon-setup-mode system
        do
            uci export $i >/root/$i.export
        done
        mv /etc/config/freifunk-bi /etc/config/freifunk-bi-tmp ||:
        ) > /root/migrate-ffbi-phase-1.log 2>&1
        /etc/init.d/done boot
        reboot
    fi

    if [ -e /etc/config/freifunk-bi-tmp ]; then
        (
        set -x
        for i in gluon gluon-node-info gluon-setup-mode system
        do
            uci import $i </dev/null
            uci commit $i
            uci import $i </root/$i.export
            uci commit $i
        done
        mv /etc/config/freifunk-bi-tmp /root/freifunk.legacy ||:
        gluon-reconfigure ||:
        ) > /root/migrate-ffbi-phase-2.log 2>&1
        /etc/init.d/done boot
        reboot
    fi
}
