#!/usr/bin/lua

local util = require 'gluon.util'
local uci = require('simple-uci').cursor()

local cmdstr='/bin/ls -l /lib/gluon/domains/ 2>/dev/null| /usr/bin/wc -l && exit $?'
local rc=util.trim(util.exec(cmdstr))
local cleanup_needed=0

if rc=="0" then
	return
end

local locode = uci:get_first('gluon-node-info', 'location', 'siteselect')
if locode==nil then
    locode = uci:get_first('gluon-node-info', 'location', 'locode')
else
    cleanup_needed=1
end
if locode then
    cmdstr='wc -l /lib/gluon/domains/' .. locode .. '.json 2>/dev/null || echo 0'
    rc=util.trim(util.exec(cmdstr))
end

if locode and rc=="0" then
	io.stderr:write(string.format("Warning: invalid FFGT locode '%s' configured, ignoring.\n", locode))
	locode = nil
end

if locode then
	io.stderr:write(string.format("Information: setting FFGT locode '%s' as domain code for site.conf.\n", locode))
    uci:set('gluon', 'core', 'domain', locode)
    uci:commit('gluon')
    if cleanup_needed==1 then
        uci:delete('gluon-node-info', '@location[0]', 'siteselect')
        uci:commit('gluon-node-info')
    end
end
