#!/bin/sh

if [ ! -x /usr/sbin/iw ]; then
  echo "$0: iw binary not found."
  exit 0
fi

NUMPHY=$(iw list | grep ^Wiphy | wc -l)
if [ $NUMPHY -gt 2 ]; then
  echo "$0: found $NUMPHY radios."
  logger "$0: found $NUMPHY radios."
fi
