#!/bin/sh

HOSTNAME=$(pretty-hostname)

if [ "$HOSTNAME" = "33330-33330-Esperanza-bbd2" ]; then
    uci delete system.@system[0].pretty_hostname
    uci set system.@system[0].hostname='33330-Esperanza-bbd2'
fi

if [ "$HOSTNAME" = "ffgt-Parkbad" ]; then
    uci delete system.@system[0].pretty_hostname
    uci set system.@system[0].hostname='33332-Parkbad-1'
fi

if [ "$HOSTNAME" = "ffgt-Parkbad2" ]; then
    uci delete system.@system[0].pretty_hostname
    uci set system.@system[0].hostname='33332-Parkbad-2'
fi

if [ "$HOSTNAME" = "ffgt-a0f3c1058b90" ]; then
    uci delete system.@system[0].pretty_hostname
    uci set system.@system[0].hostname='33332-FWTest-a0f3c1058b90'
fi

if [ "$HOSTNAME" = "33330-Stadt-Guetersloh-Berliner-Platz2" ]; then
    uci set gluon-node-info.@location[0].latitude="51.9063744"
    uci set gluon-node-info.@location[0].longitude="8.378493154"
    uci set gluon-node-info.@location[0].addr='Koenigstr-2'
    chan=$(uci get wireless.radio0.channel)
    if [ "${chan}" != "5" ]; then
      uci set wireless.radio0.channel='5'
      uci commit wireless
    fi
fi

