include $(TOPDIR)/rules.mk

PKG_NAME:=ffgt-tunneldigger-fix
PKG_RELEASE:=1

include $(TOPDIR)/../package/gluon.mk

define Package/ffgt-tunneldigger-fix
  DEPENDS:=+tunneldigger
  TITLE:=FFGT version of the init skript
endef

$(eval $(call BuildPackage,ffgt-tunneldigger-fix))
