#!/bin/sh

if [ -e /etc/config/freifunk-ffbi ]; then
  echo "Cleanup on migrating FFBI-FW to 4830.org's Gluon at $(date) ..." | tee -a /root/ffbi-migration.log

  name="$(uci get system.@system[0].ffbi_hostname 2>/dev/null)"
  if [ "${name}X" != "X" ]; then
    echo "Hostname from FFBI Firmware: \"${name}\"." | tee -a /root/ffbi-migration.log
    echo "Current hostname in Gluon:   \"$(uci get system.@system[0].hostname)\"." | tee -a /root/ffbi-migration.log
    echo "Setting Hostname to \"${name}\"." | tee -a /root/ffbi-migration.log
    uci set system.@system[0].hostname="${name}" ||:
    uci get system.@system[0].ffbi_hostname ||:
    uci commit system ||:
  fi
  echo "Done cleanup on migrating FFBI-FW to 4830.org's Gluon at $(date)" | tee -a /root/ffbi-migration.log
fi
