#!/bin/sh

if [ -e /etc/config/freifunk ]; then
  echo "$0: Migrating FFBI-FW to 4830.org's Gluon at $(date) ..." | tee -a /root/ffbi-migration.log
  echo "echo \"\$0: Executing FFBI migration to Gluon at $(date) ...\" | tee -a /root/ffbi-migration.log" >/tmp/ffbi-migration.sh
  chmod -x /tmp/ffbi-migration.sh

  # Get former firmware's settings
  domain=$(uci get freifunk.@settings[0].community | sed -e s/badoeynhausen/boy/ -e s/bielefeld/bfe/ -e s/minden/mid/)
  lat="$(uci get freifunk.@settings[0].latitude 2>/dev/null || echo 0)"
  lon="$(uci get freifunk.@settings[0].longitude 2>/dev/null || echo 0)"
  contact="$(uci get freifunk.@settings[0].contact 2>/dev/null)"
  name="$(uci get freifunk.@settings[0].name 2>/dev/null)"
  showonmap="$(uci get freifunk.@settings[0].publish_map)"

  # Move the triggering file out of the way, we're done with it anyway now
  mv /etc/config/freifunk /root/freifunk-ffbi ||:

  # Get Gluon firmware's settings, delete leftovers from FFBI
  rm /etc/uhttpd.crt /etc/uhttpd.key ||:
  for i in etc/config/autoupdater etc/sysupgrade.conf
  do
    if [ -e /rom/$i ]; then
      cp -p /rom/$i /$i
    else
      if [ -e /$i ]; then
        rm /$i
      fi
    fi
  done

  for i in $(cd /etc/config ; echo *)
  do
    rm /etc/config/$i ||:
    if [ -e /rom/etc/config/$i ]; then
      cp -p /rom/etc/config/$i /etc/config/$i ||:
    fi
  done

  # Now work on the values rescued, builing a commandfile to auto-configure this node accordingly.
  if [ ! -e /lib/gluon/domains/${domain}.json ]; then
   echo "No match for mesh ${domain} in /lib/gluon/domains/, setting do default (zzz)." | tee -a /root/ffbi-migration.log
   domain=zzz
  fi
  echo "Selected mesh: ${domain}." | tee -a /root/ffbi-migration.log

  # Convert into Gluon setting
  echo "Setting mesh domain: ${domain}." | tee -a /root/ffbi-migration.log
  echo "uci set gluon.core.domain=\"${domain}\" ||:" >>/tmp/ffbi-migration.sh
  echo "uci set gluon.core.migrated_from=ffbi ||:"   >>/tmp/ffbi-migration.sh

  echo "Hostname from FFBI Firmware: \"${name}\"." | tee -a /root/ffbi-migration.log

  mac="$(echo -e "local util = require 'gluon.util'\nlocal mac=string.sub(util.node_id(), 9);\nprint(mac);" | /usr/bin/lua)"
  if [ "${mac}X" = "X" ]; then
    mac="no-mac"
  fi

  if [ "${name}X" = "X" ]; then
    name="migrated-$(/bin/cat /tmp/sysinfo/board_name)-${mac}"
  fi
  name="$(echo ${name} | sed -e 's/ /-/g' -e 's/_/-/g' -e 's/ä/ae/g' -e 's/ö/oe/g' -e 's/ü/ue/g' -e 's/ß/sz/g' -e 's/Ä/Ae/g' -e 's/Ö/Oe/g' -e 's/Ü/Ue/g')"

  if [ "X${contact}" != "X" ]; then
    echo "uci set gluon-node-info.@owner[0].contact=\"$contact\" ||:"  >>/tmp/ffbi-migration.sh
  fi

  echo "uci set gluon-node-info.@location[0].latitude=\"$lat\" ||:"    >>/tmp/ffbi-migration.sh
  echo "uci set gluon-node-info.@location[0].longitude=\"$lon\" ||:"   >>/tmp/ffbi-migration.sh

  if [ "${showonmap}" = "none" ]; then
    echo "uci set gluon-node-info.@location[0].share_location='0' ||:" >>/tmp/ffbi-migration.sh
  else
    echo "uci set gluon-node-info.@location[0].share_location='1' ||:" >>/tmp/ffbi-migration.sh
  fi

  echo "Setting new Hostname \"${name}\"." | tee -a /root/ffbi-migration.log

  echo "uci set system.@system[0].hostname=\"$name\" ||:"              >>/tmp/ffbi-migration.sh

  if [ ! -e /etc/config/system ]; then
    echo -e >/etc/config/system "config system\n\toption timezone 'CET-1CEST,M3.5.0,M10.5.0/3'"
  fi
  uci get system.@system[0].hostname 2>&1 >/dev/null || uci set system.@system[0].hostname="$name" ||:
  uci set system.@system[0].ffbi_hostname="$name" ||:
  uci commit system ||:

  echo "uci commit gluon-node-info ||:"                                >>/tmp/ffbi-migration.sh
  echo "uci commit system ||:"                                         >>/tmp/ffbi-migration.sh
  echo "uci commit ||:"                                                >>/tmp/ffbi-migration.sh

  echo "uci set gluon-setup-mode.@setup_mode[0].configured='1' ||:"    >>/tmp/ffbi-migration.sh
  echo "uci set gluon-setup-mode.@setup_mode[0].enabled='0' ||:"       >>/tmp/ffbi-migration.sh
  echo "uci commit gluon-setup-mode ||:"                               >>/tmp/ffbi-migration.sh

  echo "echo \"\$0: Done migrating FFBI-FW to 4830.org's Gluon at $(date)\" | tee -a /root/ffbi-migration.log" >>/tmp/ffbi-migration.sh
  chmod +x /tmp/ffbi-migration.sh
  echo "$0: Done preparing migration from FFBI-FW to 4830.org's Gluon at $(date) ..." | tee -a /root/ffbi-migration.log

  echo "$0: Running /tmp/ffbi-migration.sh 10 secs after $(date) ..." | tee -a /root/ffbi-migration.log
  ((sleep 10 ; date ; /bin/sh -x /tmp/ffbi-migration.sh 2>&1 | tee -a /root/ffbi-migration.log)&) ||:
  mv /tmp/ffbi-migration.sh /root/ ||:

  echo "$0: Running gluon-reconfigure 15 secs after $(date) ..." | tee -a /root/ffbi-migration.log
  ((sleep 15 ; date ; gluon-reconfigure 2>&1 | tee -a /root/ffbi-migration.log)&)

  echo "$0: Running rgeo.sh 40 secs after $(date) ..." | tee -a /root/ffbi-migration.log
  ((sleep 30 ; date ; /lib/gluon/ffgt-geolocate/rgeo.sh 2>&1 | tee -a /root/ffbi-migration.log)&)

  echo "$0: Rebooting 60 secs after $(date) ..." | tee -a /root/ffbi-migration.log
  sync
  ((sleep 60 ; /sbin/reboot)&)
fi
