#!/bin/sh
#/etc/rc.common

START=99

if [ -x /tmp/ffbi-migration.sh ]; then
  echo "$0: Running /tmp/ffbi-migration.sh at $(date) ..." | tee -a /root/ffbi-migration.log
  ((/bin/sh -x /tmp/ffbi-migration-running.sh 2>&1 | tee -a /root/ffbi-migration.log)&)
fi