#!/bin/sh

domain="zzz"

if [ $(uci get autoupdater.stable.mirror | grep fflg) ]; then
 domain="lbg"
fi

if [ ! -e /lib/gluon/domains/${domain}.json ]; then
 echo "No match for mesh ${domain} in /lib/gluon/domains/, setting to default (zzz)." | tee -a /tmp/multidomain-migration.log
 domain=zzz
fi

if [ "${domain}" = "lbg" ]; then
 echo "Migrating FFLG-FW to Unified Firmware ..." | tee -a /tmp/multidomain-migration.log
 echo "Selected Domain: ${domain}." | tee -a /tmp/multidomain-migration.log

 curdom=$(uci get gluon.core.domain)
 if [ "${curdom}" != "${domain}" ]; then
  echo "Setting domain: ${domain}." | tee -a /tmp/multidomain-migration.log
  uci set gluon.core.domain=${domain} ||:
  uci commit gluon ||:
  gluon-reconfigure 2>&1 | tee -a /tmp/multidomain-migration.log
 else
  echo "Domain ${domain} already set." | tee -a /tmp/multidomain-migration.log
 fi
fi


